# Generated by Django 5.2 on 2025-05-31 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('armor', models.CharField(blank=True, max_length=100)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
