# Generated by Django 5.2 on 2025-04-29 09:17

from django.db import migrations, models



def create_initial_cars(apps, schema_editor):
    Car = apps.get_model('main', 'Car')
    Car.objects.create(name="KUZANAGI CT-3X")
    Car.objects.create(name="QUADRA TURBO-R V-TECH")


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_cars),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
